name: Java Build
permissions: { }

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: 'ubuntu-22.04'
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - run: |
          git describe --tags --always
          git log --oneline
      - run: mvn --batch-mode --no-transfer-progress --errors --update-snapshots clean package -Drevision=$(git describe --tags --always)
